<script setup lang="ts">
import {ref,onMounted} from 'vue'
import {RouterLink} from 'vue-router'
import api from '@/api/client'
const numbers=ref<{sid:string;phone_number:string;friendly_name:string;capabilities:{voice:boolean;sms:boolean}}[]>([]),accounts=ref<{number:string;username:string;state:string}[]>([]),error=ref(''),loading=ref(false)
async function load(){loading.value=true;error.value='';try{const [n,a]=await Promise.all([api.get('/business/numbers'),api.get('/business/accounts')]);numbers.value=n.data.data;accounts.value=a.data.data}catch{error.value='Could not fetch owned Twilio numbers'}finally{loading.value=false}}
function assigned(n:string){return accounts.value.find(a=>a.number===n)}
const review=ref<{number:string;connections:string[];blocked:boolean}|null>(null),checking=ref(false)
async function inspect(number:string){checking.value=true;error.value='';try{review.value=(await api.get('/business/number-review',{params:{number},timeout:60000})).data}catch{error.value='Could not check this number’s connections. No changes were made.'}finally{checking.value=false}}
onMounted(load)
</script>
<template><div class="space-y-6"><div class="flex justify-between"><div><h1 class="text-2xl font-semibold">Twilio numbers</h1><p class="text-sm text-gray-500 mt-2">Live inventory of numbers already owned by your Twilio account.</p></div><button @click="load" :disabled="loading" class="border rounded px-4 py-2">Refresh from Twilio</button></div><p v-if="error" class="text-red-600">{{error}}</p><div class="bg-white dark:bg-gray-800 rounded-lg overflow-x-auto"><table class="min-w-full text-left text-sm"><thead><tr><th class="p-4">Number</th><th class="p-4">Voice / SMS</th><th class="p-4">Assigned user</th><th class="p-4">Connections</th></tr></thead><tbody><tr v-for="n in numbers" :key="n.sid" class="border-t"><td class="p-4">{{n.phone_number}}<p class="text-gray-500">{{n.friendly_name}}</p></td><td class="p-4">{{n.capabilities.voice?'Voice':'No voice'}} · {{n.capabilities.sms?'SMS':'No SMS'}}</td><td class="p-4">{{assigned(n.phone_number)?.username||'Not assigned locally'}}<p class="text-gray-500">{{assigned(n.phone_number)?.state}}</p></td><td class="p-4"><button @click="inspect(n.phone_number)" :disabled="checking" class="text-primary" :aria-label="`Check connections for ${n.phone_number}`">Check connections</button></td></tr></tbody></table></div><div v-if="review" class="glass rounded-lg p-5 space-y-3"><h2 class="font-semibold">Connections for {{review.number}}</h2><ul class="list-disc pl-5 text-sm break-all"><li v-for="c in review.connections" :key="c">{{c}}</li><li v-if="!review.connections.length">No incoming integration detected.</li></ul><p class="text-sm text-gray-500">Read-only check. These connections were not changed. Outbound-only integrations cannot all be detected.</p><p v-if="review.blocked" class="text-amber-700">Assignment blocked by a Messaging Service inbound handler.</p><button @click="review=null" class="border rounded px-3 py-2">Close</button></div><RouterLink to="/devices" class="text-primary">Assign a number from SIP Users →</RouterLink></div></template>
