<script setup lang="ts">
import {ref,onMounted} from 'vue'
import {RouterLink} from 'vue-router'
import api from '@/api/client'
import {list,dateTime} from '@/utils/display'
const status=ref<Record<string,string|boolean>>({}),audit=ref<{id:number;action:string;subject:string;outcome:string;created_at:string}[]>([]),error=ref(''),notice=ref(''),busy=ref(false)
const loaded=ref(false)
const backups=ref<{filename:string;created_at:string;size:number}[]>([])
async function load(){error.value='';try{const [s,a,b]=await Promise.all([api.get('/business/status'),api.get('/business/audit'),api.get('/system/backups')]);status.value=s.data;audit.value=list(a.data.data);backups.value=list(b.data);loaded.value=true}catch{error.value='Could not load service status'}}
async function backup(){busy.value=true;error.value='';try{await api.post('/system/backups');await load()}catch{error.value='Backup could not complete'}finally{busy.value=false}}
async function verify(filename:string){busy.value=true;try{await api.post('/system/backups/verify',{filename});notice.value='Database integrity verified'}catch{error.value='Backup verification failed'}finally{busy.value=false}}
onMounted(load)
</script>
<template><div class="space-y-6"><div class="flex flex-wrap items-start justify-between gap-4"><h1 class="text-2xl font-semibold">Business phone system</h1><button @click="load" class="border rounded px-4 py-2">Refresh</button></div><p v-if="error" class="text-red-600">{{error}}</p><p v-if="notice" role="status" class="text-green-500">{{notice}}</p><div class="grid md:grid-cols-3 gap-4"><div class="bg-white dark:bg-gray-800 rounded-lg p-5"><p class="text-gray-500">SIP / audio server</p><p class="font-semibold mt-2">{{!loaded?'Checking…':status.pbx_healthy?'Healthy':'Needs attention'}}</p></div><div class="bg-white dark:bg-gray-800 rounded-lg p-5"><p class="text-gray-500">Twilio credentials</p><p class="font-semibold mt-2">{{!loaded?'Checking…':status.twilio_configured?'Configured in environment':'Missing'}}</p></div><div class="bg-white dark:bg-gray-800 rounded-lg p-5"><p class="text-gray-500">Phone security</p><p class="font-semibold mt-2">TLS / SRTP</p></div></div><div class="bg-white dark:bg-gray-800 rounded-lg p-5 space-y-3"><h2 class="font-semibold">Manage your team</h2><p>Create SIP users, assign owned Twilio numbers, and download phone setup instructions.</p><RouterLink to="/devices" class="text-primary">Open SIP Users →</RouterLink><p class="text-sm text-gray-500">The web console is restricted to administrators. SIP users access their calls and SMS through their phones.</p></div><div class="bg-white dark:bg-gray-800 rounded-lg p-5 space-y-3"><div class="flex flex-wrap items-start justify-between gap-4"><h2 class="font-semibold">Database backups</h2><button @click="backup" :disabled="busy" class="border rounded px-3 py-2">Create backup</button></div><p class="text-sm">Last daily backup: {{dateTime(typeof status.last_backup==='string'?status.last_backup:undefined)}}</p><p class="text-sm text-gray-500">Daily VPS backups include the database and private PBX credentials. Database snapshots below can be verified here. Recovery of a whole server also requires the private PBX backup and Coolify environment.</p><div v-for="b in backups.slice(0,10)" :key="b.filename" class="flex flex-wrap justify-between gap-2 border-t pt-2 text-sm"><span>{{b.filename}} · {{Math.round(b.size/1024)}} KB</span><button @click="verify(b.filename)" :disabled="busy" class="text-primary">Verify</button></div></div><div class="bg-white dark:bg-gray-800 rounded-lg p-5"><h2 class="font-semibold mb-3">Recent account changes</h2><div v-for="a in audit.slice(0,20)" :key="a.id" class="border-t py-2 text-sm">{{dateTime(a.created_at)}} · {{a.action}} · {{a.subject}} · {{a.outcome}}</div><p v-if="!audit.length" class="text-gray-500">No provisioning changes recorded yet.</p></div></div></template>
