<script setup lang="ts">
import {ref,onMounted} from 'vue'
import {RouterLink} from 'vue-router'
import api from '@/api/client'
const current=ref(''),next=ref(''),confirm=ref(''),message=ref(''),busy=ref(false)
const prefixes=ref(''),smsLimit=ref(20),policyMessage=ref('')
onMounted(async()=>{try{const p=(await api.get('/business/policy')).data;prefixes.value=p.allowed_prefixes.join(', ');smsLimit.value=p.sms_per_minute}catch{policyMessage.value='Could not load usage controls'}})
async function policy(){busy.value=true;try{await api.put('/business/policy',{allowed_prefixes:prefixes.value.split(',').map(p=>p.trim()).filter(Boolean),sms_per_minute:smsLimit.value});policyMessage.value='Usage controls saved'}catch{policyMessage.value='Use prefixes such as +44, +91 and an SMS limit from 1 to 120'}finally{busy.value=false}}
async function change(){message.value='';if(next.value!==confirm.value){message.value='Passwords do not match';return}busy.value=true;try{await api.put('/me/password',{current_password:current.value,new_password:next.value});message.value='Administrator password changed';current.value='';next.value='';confirm.value=''}catch(e){message.value=(e as {response?:{data?:{error?:{message?:string}}}}).response?.data?.error?.message||'Password could not be changed'}finally{busy.value=false}}
</script>
<template><div class="space-y-6"><h1 class="text-2xl font-semibold">Settings</h1><form @submit.prevent="change" class="bg-white dark:bg-gray-800 rounded-lg p-6 max-w-lg space-y-4"><h2 class="font-semibold">Change your administrator password</h2><label class="block">Current password<input v-model="current" type="password" autocomplete="current-password" required class="block w-full border rounded p-2 mt-1 dark:bg-gray-700"/></label><label class="block">New password<input v-model="next" type="password" autocomplete="new-password" minlength="12" required class="block w-full border rounded p-2 mt-1 dark:bg-gray-700"/></label><label class="block">Confirm password<input v-model="confirm" type="password" autocomplete="new-password" required class="block w-full border rounded p-2 mt-1 dark:bg-gray-700"/></label><p>{{message}}</p><button :disabled="busy" class="bg-primary text-white rounded px-4 py-2">Change password</button></form><form @submit.prevent="policy" class="bg-white dark:bg-gray-800 rounded-lg p-6 space-y-4 max-w-lg"><h2 class="font-semibold">Usage controls</h2><label class="block">Allowed international prefixes<input v-model="prefixes" placeholder="+44, +91" class="block w-full border rounded p-2 mt-1 dark:bg-gray-700"/></label><p class="text-sm text-gray-500">Comma-separated prefixes for outgoing calls and SMS. An empty field allows all destinations. Choose only the countries your team needs.</p><label class="block">SMS per minute per number<input v-model.number="smsLimit" type="number" min="1" max="120" required class="block w-full border rounded p-2 mt-1 dark:bg-gray-700"/></label><p class="text-sm text-gray-500">Up to two concurrent outgoing calls per SIP user.</p><p>{{policyMessage}}</p><button :disabled="busy" class="bg-primary text-white rounded px-4 py-2">Save usage controls</button></form><div class="bg-white dark:bg-gray-800 rounded-lg p-6 space-y-3"><h2 class="font-semibold">Server configuration</h2><p>Twilio Account SID and Auth Token are managed in Coolify environment variables. TLS certificates renew automatically; phones use SRTP.</p><p>Call routing and voicemail rules can be managed under Call Routing. User provisioning is managed under SIP Users.</p><RouterLink to="/" class="block text-primary">Service health, backups and change history →</RouterLink><RouterLink to="/users" class="block text-primary">Manage web console administrators →</RouterLink></div></div></template>
