<script setup lang="ts">
import {ref} from 'vue'
import {useRouter} from 'vue-router'
import {setupApi} from '@/api/auth'
import {useAuthStore} from '@/stores/auth'
const email=ref(''),password=ref(''),confirmation=ref(''),error=ref(''),busy=ref(false)
const router=useRouter(),auth=useAuthStore()
async function save(){error.value='';if(password.value!==confirmation.value){error.value='Passwords do not match';return}busy.value=true;try{await setupApi.complete({admin_email:email.value,admin_password:password.value});auth.setupCompleted=true;if(await auth.login(email.value,password.value))router.push('/');else router.push('/login')}catch(e){error.value=(e as {response?:{data?:{error?:{message?:string}}}}).response?.data?.error?.message||'Setup could not complete'}finally{busy.value=false}}
</script>
<template><div class="public-page min-h-[100dvh] flex items-center justify-center p-4 sm:p-6"><form @submit.prevent="save" class="glass rounded-xl p-5 sm:p-8 w-full max-w-lg space-y-5"><p class="gradient-text font-heading font-bold text-xl">LEADOMI SIP</p><h1 class="text-3xl">Create your administrator</h1><p class="text-gray-500 text-sm">First-time console setup. Twilio credentials are managed on the server. This step does not connect or assign any phone numbers.</p><label class="block">Email<input v-model="email" type="email" required autocomplete="username" class="block w-full border rounded p-3 mt-2" /></label><label class="block">Password<input v-model="password" type="password" required minlength="12" maxlength="72" autocomplete="new-password" class="block w-full border rounded p-3 mt-2" /></label><label class="block">Confirm password<input v-model="confirmation" type="password" required autocomplete="new-password" class="block w-full border rounded p-3 mt-2" /></label><p class="text-gray-500 text-sm">Use 12–72 characters. Keep administrator access limited to trusted staff.</p><p v-if="error" role="alert" class="text-red-600">{{error}}</p><button :disabled="busy" class="bg-primary text-white rounded-lg py-3 px-5 w-full">{{busy?'Creating administrator…':'Create administrator'}}</button></form></div></template>
