<script setup lang="ts">
import { ref, onMounted, onUnmounted, computed } from 'vue'
import api from '@/api/client'
interface Account { id:number;name:string;username:string;number:string;state:string;enabled:boolean;online:boolean }
interface NumberRecord {sid:string;phone_number:string;friendly_name:string;capabilities:{voice:boolean;sms:boolean}}
const accounts=ref<Account[]>([]),numbers=ref<NumberRecord[]>([]),server=ref(''),proxy=ref('')
const loading=ref(false),saving=ref(false),error=ref(''),showForm=ref(false),editing=ref<Account|null>(null)
const form=ref({name:'',username:'',number:'',reset_password:false})
const credentials=ref<{username:string;password:string;number:string;proxy:string;server:string}|null>(null)
const availableNumbers=computed(()=>numbers.value.filter(n=>n.capabilities.voice&&n.capabilities.sms&&!accounts.value.some(a=>a.number===n.phone_number&&a.enabled&&a.id!==editing.value?.id)))
function errorText(e:unknown){return (e as {response?:{data?:{error?:{message?:string}}}}).response?.data?.error?.message||'The request could not complete. Refresh and check the account status before retrying.'}
async function refresh(){loading.value=true;try{const res=await api.get('/business/accounts');accounts.value=res.data.data;server.value=res.data.server;proxy.value=res.data.proxy}catch(e){error.value=errorText(e)}finally{loading.value=false}}
async function open(account:Account|null=null){editing.value=account;credentials.value=null;error.value='';form.value={name:account?.name||'',username:account?.username||'',number:account?.number||'',reset_password:false};showForm.value=true;try{numbers.value=(await api.get('/business/numbers')).data.data}catch(e){error.value=errorText(e)}}
async function save(){saving.value=true;error.value='';try{const payload=editing.value?{name:form.value.name,number:form.value.number,reset_password:form.value.reset_password}:{...form.value};const res=editing.value?await api.put(`/business/accounts/${editing.value.id}`,payload,{timeout:120000}):await api.post('/business/accounts',payload,{timeout:120000});credentials.value=res.data;showForm.value=false;await refresh()}catch(e){error.value=errorText(e);await refresh()}finally{saving.value=false}}
async function disable(a:Account){if(!confirm(`Disable ${a.username}? New calls and messages will be blocked. Existing history and your Twilio number will be kept. A call already in progress may continue.`))return;saving.value=true;error.value='';try{await api.post(`/business/accounts/${a.id}/disable`,undefined,{timeout:120000})}catch(e){error.value=errorText(e)}finally{await refresh();saving.value=false}}
function download(){if(!credentials.value)return;const c=credentials.value;const text=`GoSIP phone setup\nNumber: ${c.number}\nUsername: ${c.username}\nPassword: ${c.password||'Use your existing phone password'}\nSIP identity: sip:${c.username}@${c.server}\nRegistrar URI: ${c.proxy}\nOutbound SIP Proxy URI: ${c.proxy}\nTransport: TLS, port 5061\nMedia encryption: SRTP\nUse CPIM in basic conversations: OFF\nCalls: dial +country-code-number\nMessages: sip:+country-code-number@${c.server}\nOne phone per SIP account. Keep this file private.\n`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download=`${c.username}-phone-setup.txt`;a.click();URL.revokeObjectURL(url)}
let timer:ReturnType<typeof setInterval>
onMounted(()=>{refresh();timer=setInterval(()=>{if(!saving.value)refresh()},15000)})
onUnmounted(()=>{clearInterval(timer);credentials.value=null})
</script>
<template>
 <div class="space-y-6">
  <div class="flex flex-wrap justify-between gap-4"><div><h1 class="text-2xl font-semibold">SIP Users</h1><p class="text-sm text-gray-500 mt-2">Create a phone login and assign an existing Twilio number. Calls and SMS use the assigned number.</p></div><div class="flex gap-2"><button @click="refresh" :disabled="loading||saving" class="border rounded px-4 py-2">Refresh</button><button @click="open()" :disabled="saving" class="bg-primary text-white rounded px-4 py-2">Add SIP user</button></div></div>
  <p v-if="error" role="alert" class="p-4 rounded bg-red-50 text-red-800">{{error}}</p>
  <div v-if="credentials" class="bg-green-50 text-gray-900 border border-green-200 rounded-lg p-5 space-y-3"><h2 class="font-semibold">Account provisioned</h2><p>{{credentials.username}} · {{credentials.number}}</p><p v-if="credentials.password">Phone password — shown only here: <code class="break-all select-all">{{credentials.password}}</code></p><p v-else>Continue using the existing phone password.</p><p class="text-sm">Download the setup file before closing this panel. Configuration applies within 10 seconds.</p><div class="flex gap-3"><button @click="download" class="border rounded px-3 py-2">Download phone setup</button><button @click="credentials=null" class="border rounded px-3 py-2">Close</button></div></div>
  <div class="bg-white dark:bg-gray-800 shadow rounded-lg overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-gray-50 dark:bg-gray-700"><tr><th class="p-4">User</th><th class="p-4">Assigned number</th><th class="p-4">Status</th><th class="p-4">Actions</th></tr></thead><tbody><tr v-for="a in accounts" :key="a.id" class="border-t"><td class="p-4"><p class="font-medium">{{a.name}}</p><p class="text-gray-500">{{a.username}}</p></td><td class="p-4">{{a.number||'Unassigned'}}</td><td class="p-4"><span>{{a.state}}</span><p class="text-gray-500">{{a.online?'Phone connected':'Phone offline'}}</p></td><td class="p-4"><div class="flex flex-wrap gap-3"><button @click="open(a)" :disabled="saving" class="text-primary">{{a.state==='ready'?'Edit / reset password':'Configure / retry'}}</button><button @click="disable(a)" :disabled="saving" class="text-red-600">{{a.enabled?'Disable':'Retry revocation'}}</button></div></td></tr><tr v-if="!accounts.length"><td colspan="4" class="p-6 text-gray-500">No SIP users yet. Add one to configure a phone.</td></tr></tbody></table></div>
  <div class="bg-white dark:bg-gray-800 rounded-lg p-5 space-y-2"><h2 class="font-semibold">Linphone setup</h2><p class="text-sm">Server: {{server}} · TLS port 5061 · SRTP enabled</p><p class="text-sm break-all">Set both Registrar URI and Outbound SIP Proxy URI to <code>{{proxy}}</code>.</p><p class="text-sm">Turn off “Use CPIM in basic conversations”. Dial international numbers beginning with +. For SMS, use sip:+number@{{server}}. Each SIP user supports one registered phone.</p><p class="text-sm text-gray-500">These are phone accounts. Web console administrators are managed separately.</p></div>
  <div v-if="showForm" class="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4"><form @submit.prevent="save" class="bg-white dark:bg-gray-800 rounded-lg p-6 w-full max-w-lg space-y-4 max-h-[90vh] overflow-y-auto"><h2 class="text-xl font-semibold">{{editing?'Configure SIP user':'New SIP user'}}</h2><label class="block">Name<input v-model="form.name" required maxlength="128" class="block w-full border rounded p-2 mt-1 dark:bg-gray-700" /></label><label class="block">SIP username<input v-model="form.username" :disabled="!!editing" required pattern="[A-Za-z][A-Za-z0-9_-]{2,63}" class="block w-full border rounded p-2 mt-1 dark:bg-gray-700" /></label><label class="block">Twilio number<select v-model="form.number" required class="block w-full border rounded p-2 mt-1 dark:bg-gray-700"><option value="">Select an available number</option><option v-for="n in availableNumbers" :key="n.sid" :value="n.phone_number">{{n.phone_number}} {{n.friendly_name}}</option></select></label><p v-if="!availableNumbers.length" class="text-sm text-amber-700">No unassigned numbers with voice and SMS are available. Existing numbers are kept with their assigned users.</p><label v-if="editing" class="flex gap-2"><input v-model="form.reset_password" type="checkbox" />Generate a new phone password (requires updating the phone)</label><p class="text-sm text-gray-500">Creates or updates the Twilio SIP credential, assigns caller ID, and configures incoming calls and SMS. This updates the selected number’s Twilio webhooks and default call route.</p><p v-if="error" class="text-red-600">{{error}}</p><div class="flex justify-end gap-3"><button type="button" @click="showForm=false" :disabled="saving" class="border rounded px-4 py-2">Cancel</button><button :disabled="saving||!form.number" class="bg-primary text-white rounded px-4 py-2">{{saving?'Provisioning…':'Save and provision'}}</button></div></form></div>
 </div>
</template>
