<script setup lang="ts">
import { ref, onMounted, onUnmounted, computed, watch } from 'vue'
import api from '@/api/client'
interface Account { id:number;name:string;username:string;number:string;state:string;enabled:boolean;online:boolean }
interface NumberRecord {sid:string;phone_number:string;friendly_name:string;capabilities:{voice:boolean;sms:boolean}}
const accounts=ref<Account[]>([]),numbers=ref<NumberRecord[]>([]),server=ref(''),proxy=ref('')
interface Review {number:string;connections:string[];fingerprint:string;blocked:boolean}
const reassign=ref(false)
const review=ref<Review|null>(null),reviewLoading=ref(false),confirmed=ref(false)
const changesNumber=computed(()=>!editing.value||editing.value.number!==form.value.number||editing.value.state!=='ready'||!editing.value.enabled)
const loading=ref(false),saving=ref(false),error=ref(''),showForm=ref(false),editing=ref<Account|null>(null)
const form=ref({name:'',username:'',number:'',reset_password:false,password:'',number_review:''})
watch(()=>[form.value.number,editing.value?.id,showForm.value] as const,async ([number])=>{review.value=null;confirmed.value=false;if(!showForm.value||!number||!changesNumber.value)return;reviewLoading.value=true;try{const res=await api.get('/business/number-review',{params:{number},timeout:60000});if(form.value.number===number)review.value=res.data}catch(e){error.value=errorText(e)}finally{reviewLoading.value=false}})
const credentials=ref<{username:string;password:string;number:string;proxy:string;server:string}|null>(null)
const availableNumbers=computed(()=>(editing.value&&!numbers.value.some(n=>n.phone_number===editing.value?.number)?[...numbers.value,{sid:'assigned',phone_number:editing.value.number,friendly_name:'',capabilities:{voice:true,sms:true}}]:numbers.value).filter(n=>(!editing.value||reassign.value||n.phone_number===editing.value.number)&&n.capabilities.voice&&n.capabilities.sms&&!accounts.value.some(a=>a.number===n.phone_number&&a.enabled&&a.id!==editing.value?.id)))
function errorText(e:unknown){return (e as {response?:{data?:{error?:{message?:string}}}}).response?.data?.error?.message||'The request could not complete. Refresh and check the account status before retrying.'}
async function refresh(){loading.value=true;try{const res=await api.get('/business/accounts');accounts.value=res.data.data;server.value=res.data.server;proxy.value=res.data.proxy}catch(e){error.value=errorText(e)}finally{loading.value=false}}
async function open(account:Account|null=null){editing.value=account;reassign.value=!!account&&account.state!=='ready';credentials.value=null;error.value='';form.value={name:account?.name||'',username:account?.username||'',number:account?.number||'',reset_password:false,password:'',number_review:''};review.value=null;confirmed.value=false;showForm.value=true;try{numbers.value=(await api.get('/business/numbers')).data.data}catch(e){error.value=errorText(e)}}
async function save(){if(changesNumber.value&&(!review.value||review.value.blocked||!confirmed.value))return;saving.value=true;error.value='';try{const payload=editing.value?{name:form.value.name,number:form.value.number,reset_password:form.value.reset_password,password:form.value.reset_password?form.value.password:'',number_review:confirmed.value?review.value?.fingerprint:''}:{...form.value,number_review:confirmed.value?review.value?.fingerprint:''};const res=editing.value?await api.put(`/business/accounts/${editing.value.id}`,payload,{timeout:120000}):await api.post('/business/accounts',payload,{timeout:120000});credentials.value=res.data;showForm.value=false;form.value.password='';await refresh()}catch(e){error.value=errorText(e);await refresh()}finally{saving.value=false}}
async function disable(a:Account){if(!confirm(`Disable ${a.username}? New calls and messages will be blocked. Existing history and your Twilio number will be kept. A call already in progress may continue.`))return;saving.value=true;error.value='';try{await api.post(`/business/accounts/${a.id}/disable`,undefined,{timeout:120000})}catch(e){error.value=errorText(e)}finally{await refresh();saving.value=false}}
function download(){if(!credentials.value)return;const c=credentials.value;const text=`Leadomi SIP phone setup\nNumber: ${c.number}\nUsername: ${c.username}\nPassword: ${c.password||'Use your existing phone password'}\nSIP identity: sip:${c.username}@${c.server}\nRegistrar URI: ${c.proxy}\nOutbound SIP Proxy URI: ${c.proxy}\nTransport: TLS, port 5061\nMedia encryption: SRTP\nUse CPIM in basic conversations: OFF\nCalls: dial +country-code-number\nMessages: sip:+country-code-number@${c.server}\nOne phone per SIP account. Keep this file private.\n`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download=`${c.username}-phone-setup.txt`;a.click();URL.revokeObjectURL(url)}
let timer:ReturnType<typeof setInterval>
onMounted(()=>{refresh();timer=setInterval(()=>{if(!saving.value)refresh()},15000)})
onUnmounted(()=>{clearInterval(timer);credentials.value=null})
</script>
<template>
 <div class="space-y-6">
  <div class="flex flex-wrap justify-between gap-4"><div><h1 class="text-2xl font-semibold">SIP Users</h1><p class="text-sm text-gray-500 mt-2">Create a phone login and assign an existing Twilio number. Calls and SMS use the assigned number.</p></div><div class="flex gap-2"><button @click="refresh" :disabled="loading||saving" class="border rounded px-4 py-2">Refresh</button><button @click="open()" :disabled="saving" class="bg-primary text-white rounded px-4 py-2">Add SIP user</button></div></div>
  <p v-if="error" role="alert" class="p-4 rounded bg-red-50 text-red-800">{{error}}</p>
  <div v-if="credentials" class="bg-green-50 text-gray-900 border border-green-200 rounded-lg p-5 space-y-3"><h2 class="font-semibold">Account provisioned</h2><p>{{credentials.username}} · {{credentials.number}}</p><p v-if="credentials.password">Phone password — shown only here: <code class="break-all select-all">{{credentials.password}}</code></p><p v-else>Continue using the existing phone password.</p><p class="text-sm">Download the setup file before closing this panel. Configuration applies within 10 seconds.</p><div class="flex gap-3"><button @click="download" class="border rounded px-3 py-2">Download phone setup</button><button @click="credentials=null" class="border rounded px-3 py-2">Close</button></div></div>
  <div class="bg-white dark:bg-gray-800 shadow rounded-lg overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-gray-50 dark:bg-gray-700"><tr><th class="p-4">User</th><th class="p-4">Assigned number</th><th class="p-4">Status</th><th class="p-4">Actions</th></tr></thead><tbody><tr v-for="a in accounts" :key="a.id" class="border-t"><td class="p-4"><p class="font-medium">{{a.name}}</p><p class="text-gray-500">{{a.username}}</p></td><td class="p-4">{{a.number||'Unassigned'}}</td><td class="p-4"><span>{{a.state}}</span><p class="text-gray-500">{{a.online?'Phone connected':'Phone offline'}}</p></td><td class="p-4"><div class="flex flex-wrap gap-3"><button @click="open(a)" :disabled="saving" class="text-primary">{{a.state==='ready'?'Edit / reset password':'Configure / retry'}}</button><button @click="disable(a)" :disabled="saving" class="text-red-600">{{a.enabled?'Disable':'Retry revocation'}}</button></div></td></tr><tr v-if="!accounts.length"><td colspan="4" class="p-6 text-gray-500">No SIP users yet. Add one to configure a phone.</td></tr></tbody></table></div>
  <div class="bg-white dark:bg-gray-800 rounded-lg p-5 space-y-2"><h2 class="font-semibold">Linphone setup</h2><p class="text-sm">Server: {{server}} · TLS port 5061 · SRTP enabled</p><p class="text-sm break-all">Set both Registrar URI and Outbound SIP Proxy URI to <code>{{proxy}}</code>.</p><p class="text-sm">Turn off “Use CPIM in basic conversations”. Dial international numbers beginning with +. For SMS, use sip:+number@{{server}}. Each SIP user supports one registered phone.</p><p class="text-sm text-gray-500">These are phone accounts. Web console administrators are managed separately.</p></div>
  <div v-if="showForm" class="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4"><form @submit.prevent="save" class="bg-white dark:bg-gray-800 rounded-lg p-6 w-full max-w-lg space-y-4 max-h-[90vh] overflow-y-auto"><h2 class="text-xl font-semibold">{{editing?'Configure SIP user':'New SIP user'}}</h2><label class="block">Name<input v-model="form.name" required maxlength="128" class="block w-full border rounded p-2 mt-1 dark:bg-gray-700" /></label><label class="block">SIP username<input v-model="form.username" :disabled="!!editing" required pattern="[A-Za-z][A-Za-z0-9_-]{2,63}" class="block w-full border rounded p-2 mt-1 dark:bg-gray-700" /></label><label class="block">Twilio number<select v-model="form.number" required class="block w-full border rounded p-2 mt-1 dark:bg-gray-700"><option value="">Select an available number</option><option v-for="n in availableNumbers" :key="n.sid" :value="n.phone_number">{{n.phone_number}}{{n.friendly_name&&n.friendly_name.replace(/\D/g,'')!==n.phone_number.replace(/\D/g,'')?' · '+n.friendly_name:''}}</option></select></label><button v-if="editing&&!reassign" type="button" @click="reassign=true" class="text-primary text-sm">Change assigned number</button><p v-if="!availableNumbers.length" class="text-sm text-amber-700">No unassigned numbers with voice and SMS are available. Existing numbers are kept with their assigned users.</p><label v-if="editing" class="flex gap-2"><input v-model="form.reset_password" type="checkbox" />Reset phone password (requires updating the phone)</label><label v-if="!editing||form.reset_password" class="block">Custom phone password <span class="text-gray-500">(optional)</span><input v-model="form.password" type="password" autocomplete="new-password" minlength="12" maxlength="72" pattern="[!-~]{12,72}" class="block w-full border rounded p-2 mt-1" /><span class="text-sm text-gray-500">12–72 characters, no spaces. Leave empty to generate a password. This password is for the phone; the server uses a separate Twilio credential.</span></label>
<div v-if="changesNumber&&form.number" class="border border-amber-700 rounded-lg p-4 space-y-3" aria-live="polite"><h3 class="font-semibold">Review number connections</h3><p v-if="reviewLoading">Checking Twilio and local routing…</p><template v-else-if="review"><p class="text-sm">Existing connections detected:</p><ul class="list-disc pl-5 text-sm break-all"><li v-for="connection in review.connections" :key="connection">{{connection}}</li><li v-if="!review.connections.length">No webhook, application, Messaging Service, or local route was detected.</li></ul><p class="text-sm">Assigning this number will replace its voice/SMS webhooks, application links, and default local routing. Other services may stop receiving calls or SMS. External systems that use the number only for outgoing traffic cannot be detected.</p><p v-if="editing?.number&&editing.number!==form.number" class="text-sm">The old number {{editing.number}} keeps its Twilio webhooks but loses its local call routes. It will no longer ring this user.</p><p v-if="review.blocked" role="alert" class="text-amber-400">Assignment blocked: this Messaging Service handles inbound SMS. Its settings will not be changed automatically.</p><label v-else class="flex items-start gap-2"><input v-model="confirmed" type="checkbox" class="mt-1" />I reviewed these connections and authorize assigning this number and replacing its routing.</label></template><p v-else class="text-sm">Number check failed or has not completed. Saving is blocked.</p></div>
<p v-if="!changesNumber" class="text-sm text-gray-500">The number, Twilio credentials, and call routes are preserved. Only the name and an explicitly requested phone password reset change.</p><p v-if="error" class="text-red-600">{{error}}</p><div class="flex justify-end gap-3"><button type="button" @click="showForm=false" :disabled="saving" class="border rounded px-4 py-2">Cancel</button><button :disabled="saving||!form.number||(changesNumber&&(!review||review.blocked||!confirmed||reviewLoading))" class="bg-primary text-white rounded px-4 py-2">{{saving?'Provisioning…':changesNumber?'Assign and provision':'Save changes'}}</button></div></form></div>
 </div>
</template>
