<script setup lang="ts">
import {ref,onMounted,computed} from 'vue'
import api from '@/api/client'
import {dateTime,list} from '@/utils/display'
interface Voicemail {id:number;caller_id:string;duration:number;recording_url?:string;transcript_text?:string;is_read:boolean;created_at:string}
const data=ref<Voicemail[]>([]),loading=ref(false),error=ref(''),offset=ref(0),total=ref(0)
const unread=computed(()=>data.value.filter(v=>!v.is_read).length)
async function load(){loading.value=true;error.value='';try{const r=(await api.get('/voicemails',{params:{limit:50,offset:offset.value}})).data;data.value=list(r.data);total.value=r.pagination?.total||0}catch{error.value='Could not load voicemail. Try again.'}finally{loading.value=false}}
async function read(v:Voicemail){if(v.is_read)return;try{await api.put(`/voicemails/${v.id}/read`);v.is_read=true}catch{error.value='Could not mark voicemail as read'}}
onMounted(load)
</script>
<template><div class="space-y-6"><div class="flex flex-wrap justify-between gap-4"><div><h1 class="text-3xl">Voicemails</h1><p class="text-gray-500 text-sm mt-2">{{unread}} unread on this page · {{total}} recordings. Phone message-waiting controls are not available in this deployment.</p></div><button @click="load" :disabled="loading" class="border rounded px-4 py-2">Refresh</button></div><p v-if="error" role="alert" class="text-red-600">{{error}}</p><div v-if="!data.length" class="glass rounded-lg p-8 text-gray-500">{{loading?'Loading voicemail…':'No voicemail recordings yet.'}}</div><article v-for="v in data" :key="v.id" class="glass rounded-lg p-5 space-y-3"><div class="flex flex-wrap justify-between gap-3"><div><h2 class="font-semibold">{{v.caller_id||'Unknown caller'}}</h2><p class="text-gray-500 text-sm">{{dateTime(v.created_at)}} · {{v.duration}} seconds · {{v.is_read?'Read':'Unread'}}</p></div><button v-if="!v.is_read" @click="read(v)" class="border rounded px-3 py-2 text-sm">Mark read</button></div><audio v-if="v.recording_url" controls preload="none" :src="`/api/voicemails/${v.id}/audio`" class="w-full" @ended="read(v)" @error="error='Recording could not be played. The provider recording may be unavailable.'" /><p v-else class="text-gray-500 text-sm">Recording URL is unavailable.</p><p v-if="v.transcript_text" class="whitespace-pre-wrap text-sm">{{v.transcript_text}}</p><p v-else class="text-sm text-gray-500">No transcript provided.</p></article><div class="flex justify-between"><button @click="offset=Math.max(0,offset-50);load()" :disabled="!offset||loading" class="border rounded px-4 py-2">Previous</button><button @click="offset+=50;load()" :disabled="offset+50>=total||loading" class="border rounded px-4 py-2">Next</button></div></div></template>
